apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service  # This label must match the labels used in the Deployment
  ports:
    - protocol: TCP
      port: 5000            # The port that the Service will expose externally
      targetPort: 5000     # The port your application is listening on inside the container
  type: ClusterIP          # Can change to LoadBalancer for external access, or NodePort
